#!/bin/sh
#
# Scan sysfs for nodes and trigger module loading and other coldplug business...
#


case "$1" in
	start)
		. /etc/init.d/loadmods.sh
	;;

	stop)
		:
	;;

	*)
		echo $"Usage: $0 {start|stop}"
		exit 1;
	;;
esac

exit $?
