#! /bin/sh
#
# NFS mount
#

case "$1" in
  start)
	echo "Mounting NFS..."
	/bin/mount -a
	;;
  stop)
	echo -n "Unmounting NFS..."
	/bin/umount -f -t nfs
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
